### ISSUE TITLE
Password shows `9` instead of dot

### ISSUE THREAD

**Issue by Ablu** [tales/tales-client#34]
In the past typing into the password field gave you dots representing characters of the password.

In my recent android builds it somehow started to become a `9` (tested on Nexus 7 and Moto G2).

**Comment by Ablu** [comment]
Somehow the 5.4.1 is not affected... So either this is an issue in Qt 5.5 or in the way I build qt...

**Comment by bjorn** [comment]
Yeah, I noticed this too. Probably an encoding issue, though it may be on the Qt side... Maybe something to report.

**Comment by Ablu** [comment]
If I remove line `app.setFont(QFont("DejaVu Serif"));` from main.cpp. So it seems to be a font issue?

**Comment by Ablu** [comment]
Ah. Forget last comment. I made a bad test...

**Comment by Ablu** [comment]
Filed https://bugreports.qt.io/browse/QTBUG-45169.

**Comment by bjorn** [comment]
Seems like a good idea, let's see what they say.

**Comment by Ablu** [comment]
This seems to be fixed in one of the recent automatic builds. @bjorn can you confirm this?

**Comment by bjorn** [comment]
Yes, this problem is no more on my S3. Did you upgrade the Qt version? Bug you reported still marked as Unresolved...

**Comment by Ablu** [comment]
It automatically builds at once a week and uses that for the play store
build. So it tracks git. Will close the bugreport then.

- Sent from mobile. Please excuse shortness and typing errors. (Might be
sent delayed too)
