### ISSUE TITLE
NpcDialog: choice text not wrapping

### ISSUE THREAD

**Issue by Ablu** [tales/tales-client#35]
Long choices do not wrap (can be tested with Durmark).

**Comment by bjorn** [comment]
This is either Android or Qt 5.5 specific. Note that the text is also centered. The left-alignment and wrapping is fine with Qt 5.4.1 on desktop, at least for me.

Hopefully we just need to override some different default values.

**Comment by Ablu** [comment]
I hit it with Qt 5.4.0. on pc. Will need to test with a newer version (and on android)

**Comment by Ablu** [comment]
Fixed this in 4f7b1c4183e0abe8b999873fd587cac3438793ae

**Comment by bjorn** [comment]
@Ablu Erm, the text is not actually supposed to be centered, so I think you should drop the `horizontalAlignment: Text.AlignHCenter`. I don't think this previously was the effect of `anchors.centerIn: parent`, as I commented here before, on desktop with Qt 5.4.1 the text was left-aligned.

**Comment by Ablu** [comment]
Eh... Right. http://www.sourceoftales.org/screenshots/tales2.png shows it
left aligned... I thought it was centered... Will fix that again.

**Comment by Ablu** [comment]
Fixed
