### ISSUE TITLE
Attribute rounding sometimes has a few too many digits

### ISSUE THREAD

**Issue by Ablu** [tales/tales-client#47]
![screenshot_2015-09-27-08-08-24](https://cloud.githubusercontent.com/assets/741061/10122130/820b62f2-650d-11e5-9b89-86853d867f1c.png)

See the movement speed value

**Comment by bjorn** [comment]
Strange, is this limiting of precision broken?
```qml
        AttributeLabel {
            name: qsTr("Movement speed")
            value: limitPrecision(playerAttributes.movementSpeed, 1)
        }
```

**Comment by Ablu** [comment]
See the fix. QML handeled this as `typeof number` which is a floating point number.

**Comment by bjorn** [comment]
Well, that's a funny fix. I understand that after the division, floating point inaccuracies may occur again, but why would `toString()` hide those inaccuracies while binding to the text of a label doesn't?

**Comment by Ablu** [comment]
Well if you print the number after the division it is still fine. It must be the string conversion somewhere in the qt quick engine. So I just do it in JavaScript.
